# Generated by Django 4.0 on 2023-08-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_applyform_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='birthdate',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
