# Generated by Django 4.2.4 on 2023-12-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_applyform_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='gender',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=20),
        ),
    ]
