# Generated by Django 4.2.4 on 2024-01-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_applyform_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyform',
            name='exprience_and_reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='applyform',
            name='finish_time',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='applyform',
            name='major',
            field=models.CharField(choices=[('컴퓨터공학과', '컴퓨터공학과'), ('자율전공학과', '자율전공학과')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='applyform',
            name='meeting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applyform',
            name='readiness',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='first_preference',
            field=models.CharField(choices=[('보컬', '보컬'), ('드럼', '드럼'), ('기타', '기타'), ('베이스', '베이스'), ('신디(피아노)', '신디(피아노)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='play_instrument',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='second_preference',
            field=models.CharField(choices=[('보컬', '보컬'), ('드럼', '드럼'), ('기타', '기타'), ('베이스', '베이스'), ('신디(피아노)', '신디(피아노)')], max_length=20),
        ),
    ]
