# Generated by Django 4.2.9 on 2024-02-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_applyform_experience_and_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyform',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
