# Generated by Django 4.2.2 on 2023-07-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreshmanTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.CharField(max_length=30)),
                ('phone_num', models.CharField(max_length=20, unique=True)),
                ('major', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=10)),
                ('meeting', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=20, unique=True)),
                ('member', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('phone_num', models.CharField(max_length=11)),
                ('general_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tickets.generalticket')),
            ],
        ),
    ]
