# Generated by Django 4.0 on 2023-08-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ordertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalticket',
            name='reservation_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
