# Generated by Django 4.2.4 on 2023-10-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_generalticket_reservation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalticket',
            name='reservation_id',
        ),
        migrations.AddField(
            model_name='freshmanticket',
            name='reservation_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
