# Generated by Django 4.2.4 on 2023-12-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_generalticket_reservation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalticket',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='freshmanticket',
            name='student_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
