# Generated by Django 4.2.4 on 2023-12-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_generalticket_status_alter_freshmanticket_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalticket',
            name='payment',
            field=models.CharField(default='', max_length=6),
        ),
    ]
