# Generated by Django 3.2.20 on 2024-01-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_generalticket_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshmanticket',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalticket',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
