# Generated by Django 3.2.20 on 2024-01-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_generalticket_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshmanticket',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
