# Generated by Django 4.2.4 on 2024-02-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_freshmanticket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshmanticket',
            name='meeting',
            field=models.CharField(default='불참', max_length=10),
        ),
    ]
